# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20171024_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cour',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student_attendance',
            old_name='stud',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='cour',
            new_name='course',
        ),
    ]
