# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20171024_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
